### ISSUE TITLE
Deselecting All Entries In Association For Which There Was Previously A Value Causes Error

### ISSUE THREAD

**Issue by tomjrti** [jakub-zawislak/formex_ecto#2]
When updating an error is caused if you remove  all selections for entry that previously had a selected value.

![cannot-deselect](https://user-images.githubusercontent.com/9740967/34318776-fe9a0304-e784-11e7-9f64-3b834cac67c7.png)

**Comment by jakub-zawislak** [comment]
Thanks a lot for this! I just fixed this in the main library. Please update Formex to 0.6.0
